// Code generated by MockGen. DO NOT EDIT.
// Source: platform.go

// Package ports_mocks is a generated GoMock package.
package ports_mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ports_platform "github.com/rickferrdev/gopher-login/internal/core/ports/platform"
)

// MockTokenizer is a mock of Tokenizer interface.
type MockTokenizer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenizerMockRecorder
}

// MockTokenizerMockRecorder is the mock recorder for MockTokenizer.
type MockTokenizerMockRecorder struct {
	mock *MockTokenizer
}

// NewMockTokenizer creates a new mock instance.
func NewMockTokenizer(ctrl *gomock.Controller) *MockTokenizer {
	mock := &MockTokenizer{ctrl: ctrl}
	mock.recorder = &MockTokenizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenizer) EXPECT() *MockTokenizerMockRecorder {
	return m.recorder
}

// GenerateUserToken mocks base method.
func (m *MockTokenizer) GenerateUserToken(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUserToken", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateUserToken indicates an expected call of GenerateUserToken.
func (mr *MockTokenizerMockRecorder) GenerateUserToken(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUserToken", reflect.TypeOf((*MockTokenizer)(nil).GenerateUserToken), id)
}

// ValidateUserToken mocks base method.
func (m *MockTokenizer) ValidateUserToken(token string) (*ports_platform.UserClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserToken", token)
	ret0, _ := ret[0].(*ports_platform.UserClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUserToken indicates an expected call of ValidateUserToken.
func (mr *MockTokenizerMockRecorder) ValidateUserToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserToken", reflect.TypeOf((*MockTokenizer)(nil).ValidateUserToken), token)
}

// MockHasher is a mock of Hasher interface.
type MockHasher struct {
	ctrl     *gomock.Controller
	recorder *MockHasherMockRecorder
}

// MockHasherMockRecorder is the mock recorder for MockHasher.
type MockHasherMockRecorder struct {
	mock *MockHasher
}

// NewMockHasher creates a new mock instance.
func NewMockHasher(ctrl *gomock.Controller) *MockHasher {
	mock := &MockHasher{ctrl: ctrl}
	mock.recorder = &MockHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHasher) EXPECT() *MockHasherMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockHasher) Generate(pass []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", pass)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockHasherMockRecorder) Generate(pass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockHasher)(nil).Generate), pass)
}

// Validate mocks base method.
func (m *MockHasher) Validate(hash, pass []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", hash, pass)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockHasherMockRecorder) Validate(hash, pass interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockHasher)(nil).Validate), hash, pass)
}

// MockStructValidator is a mock of StructValidator interface.
type MockStructValidator struct {
	ctrl     *gomock.Controller
	recorder *MockStructValidatorMockRecorder
}

// MockStructValidatorMockRecorder is the mock recorder for MockStructValidator.
type MockStructValidatorMockRecorder struct {
	mock *MockStructValidator
}

// NewMockStructValidator creates a new mock instance.
func NewMockStructValidator(ctrl *gomock.Controller) *MockStructValidator {
	mock := &MockStructValidator{ctrl: ctrl}
	mock.recorder = &MockStructValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStructValidator) EXPECT() *MockStructValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockStructValidator) Validate(out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", out)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockStructValidatorMockRecorder) Validate(out interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockStructValidator)(nil).Validate), out)
}
